name: Deploy Documentation

on:
  push:
    branches:
      - main  # Triggers deployment on push to the main branch
  pull_request:  # Optional - you can also build docs for pull requests
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write  # This allows pushing to the repository (necessary for Pages deployment)

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5

      # Step 3: Install dependencies from docs/requirements.txt
      - name: Install Dependencies
        run: |
          pip install -r docs/requirements.txt

      # Step 4: Build Sphinx documentation using Make
      - name: Build Documentation
        run: |
          make -C docs clean  # Clean the previous build
          rm -rf docs/_autosummary  # Remove the autosummary folder
          
          sphinx-apidoc -o docs/_autosummary/script ./script
          sphinx-apidoc -o docs/_autosummary/examples ./examples

          make -C docs html  # Rebuild the documentation

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}  # Only deploy on push to main branch
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html  # Ensure this is the correct build output directory
          force_orphan: true  # Creates an orphan gh-pages branch for clean deployments

      # Step 6: Show website URL in GitHub Action summary
      - name: Show Website URL
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}  # Only show on push to main branch
        run: |
          echo "Documentation deployed! Visit the site at: https://<YOUR_GITHUB_USERNAME>.github.io/<YOUR_REPOSITORY_NAME>/" >> $GITHUB_STEP_SUMMARY
