name: Deploy Documentation

on:
  push:
    branches:
      - main  # Triggers deployment on push to the main branch
  pull_request:  # Optional - build docs for pull requests (deployment is skipped)
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write  # Needed to push the artifact to the repository
  pages: write      # Grants permission to deploy to GitHub Pages
  id-token: write   # Needed for deployment verification with GitHub Pages

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5

      # Step 3: Install dependencies from docs/requirements.txt
      - name: Install Dependencies
        run: |
          pip install -r docs/requirements.txt
          pip install -r requirements.txt


      # Step 6: Build Sphinx documentation using Make
      - name: Build Documentation
        run: |
          make -C docs clean  # Clean the previous build
          rm -rf docs/_autosummary  # Remove the autosummary folder
          
          sphinx-apidoc -o docs/_autosummary/script ./atpp
          sphinx-apidoc -o docs/_autosummary/examples ./examples

          make -C docs html  # Rebuild the documentation

      # # Step 5: Add .nojekyll file (to prevent Jekyll processing) (!!!must be after documentation is processed!!!)
      # - name: Add .nojekyll
      #   run: touch docs/_build/html/.nojekyll


      # Step 6: Upload the built HTML files as a Pages artifact
      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/_build/html  # Ensure this is the correct build output directory

  # Step 7: Deploy to GitHub Pages when the workflow is triggered by a push
  deploy:
    needs: docs
    runs-on: ubuntu-latest
    permissions:
      pages: write  # Permissions required to deploy
      id-token: write  # Needed for token verification

    # # Deploy to the github-pages environment
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 