name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if different

permissions:
  contents: write  # Grants write permission to push to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx  # Install Sphinx
          pip install -r requirements.txt  # If you have additional requirements

      - name: Build and Deploy Documentation
        uses: ammaraskar/sphinx-action@v1.2.0
        with:
          docs-folder: 'docs'  # Replace with your docs directory if different
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: 'gh-pages'
