name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme

      - name: Build documentation
        run: |
          cd docs
          sphinx-apidoc -o docs/_autosummary ../script
          make clean
          make html

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write      # to deploy to GitHub Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      contents: write   # This grants permission to push to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html

