name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: main  # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-latest  # You can update this to ubuntu-20.04 if needed
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Use the Python version you need

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt  # Or wherever your requirements.txt is located

    - name: Clean AutoDoc Directory
      run: |
        rm -rf docs/_autosummary/script/*
        rm -rf docs/_autosummary/examples/*

    - name: Generate API Documentation
      run: |
        sphinx-apidoc -o docs/_autosummary/script ./script
        sphinx-apidoc -o docs/_autosummary/examples ./examples

    - name: Clean Sphinx Build Directory
      run: |
        make -C docs clean  # Run `make clean` inside the docs folder

    - name: Build Sphinx Documentation
      run: |
        make -C docs html  # Build the HTML documentation

    - id: deployment
      uses: sphinx-notes/pages@v3
      # with:
        # Provide any Sphinx build options here, such as the build folder
        # sphinx_build_options: --extensions=sphinx.ext.autosummary
