name: Deploy Documentation

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme

      - name: Build documentation
        run: |
          cd docs
          make html

      # Upload the build as an artifact for later use
      - name: Upload build artifact
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: github-pages
          path: ./docs/_build/html

  # Deploy job
  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Download the artifact uploaded from the build job
      - name: Download build artifact
        uses: actions/download-artifact@v3  # Updated to v3
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
