name: Update README v2

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set Git user
      run: |
        git config --global user.email "lcsantoro97@gmail.com"
        git config --global user.name "Luca Santoro"

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        pip install jinja2 pypandoc

    - name: Get the latest release tag
      id: get_latest_release
      run: echo "tag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

    - name: Run the README generation script
      run: |
        python generate_readme.py

    - name: Update README
      run: |
        latest_release=$tag
        sed -i "s/^\\- \\*\\*Version\\*\\*: .*/- **Version**: $latest_release/" README.md

    - name: Check if README.md is modified
      run: |
        git add README.md
        git diff --cached --exit-code || git commit -m "Automatically updated README.md"
        git push origin main || echo "No changes to push"
